home_link: "https://www.railstutorial.org/"
help_link: "https://www.railstutorial.org/help"
book_link: "https://www.railstutorial.org/book"
logo_link: "rails.png"
ruby_on_rails_link: "https://rubyonrails.org/"
about_link: "https://www.railstutorial.org/book"
contact_link: "https://www.railstutorial.org/book"
